apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: qe-coordinator
  labels:
    app: qe-coordinator
spec:
  selector:
    matchLabels:
      app: qe-coordinator
      role: master
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: qe-coordinator
        role: master
        tier: backend
    spec:
      containers:
      - name: qe-coordinator
        image: qe-coordinator:52
        imagePullPolicy: Never
        resources:
          requests:
            cpu: 512m
            memory: 1024Mi
        ports:
        - containerPort: 4567

