apiVersion: v1
kind: Service
metadata:
  name: qe-coordinator
  labels:
    app: qe-coordinator
    role: master
    tier: backend
spec:
  ports:
  - port: 4567
    targetPort: 4567
  selector:
    app: qe-coordinator
    role: master
    tier: backend